baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme= "ga-hugo-theme"
[taxonomies]
  category = "categories"
  tag = "tags"
  difficulte = "difficulte"
  genres = "genres"

